### ISSUE TITLE
Think about how to merge into CPLEX.jl

### ISSUE THREAD

**Issue by odow** [iSoron/CPLEXW#1]
It'd be nice to merge this into the main body of CPLEX.jl, along with the script to regenerate things.

We'd probably want things a little more user-friendly, so if you had any ideas, please share.

**Comment by iSoron** [comment]
I have added the code generation script to the repository. There's also now a simple README showing how to use this package (by itself and in conjunction with `CPLEX.jl`) and how to regenerate the wrapper.

Could you clarify what do you mean by making things more user-friendly? Do you mean adding things like `add_constr!(model, [1., 2., 1.], '<', 15.)` that you have in Gurobi.jl? I would personally not be very interested in this, since we already have JuMP.

**Comment by odow** [comment]
Hmm. Actually you are correct. The complexity should be in the MOI wrapper, not in the C API.

**Comment by odow** [comment]
The full C API is now wrapped by CPLEX.jl: 
- https://github.com/jump-dev/CPLEX.jl 
- https://discourse.julialang.org/t/ann-upcoming-breaking-changes-to-cplex-jl-and-gurobi-jl/47814
